global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: hooklook
    metrics_path: /metrics
    static_configs:
      - targets: ['hooklook:9999'] # intentionally wrong
      # - targets: ['hooklook:9092'] # correct